# -*- coding: utf-8 -*-
"""Recategorization analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NDk3kYxTVsijZdgmszSYtjJj-jhzqmqn

This notebook simply investigates changes before and after recategorization. What % of responses were recategorized, Cohens Kappa score, changes per topic.
"""

from google.colab import drive
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
drive.mount('/content/drive')

from sklearn.metrics import cohen_kappa_score

project_folder = '/content/drive/MyDrive/ProjectSafe_CleanCode/data/Recategorization/'
data_path = project_folder + 'recategorized_13_full.csv'
recat = pd.read_csv(data_path)
recat.head()

recat

"""Compute Cohen's Kappa (Agreement Score)
This tells us how much the LLM agrees with the original topic modeling **beyond chance**.

A value close to 1 = strong agreement and little change
A value close to or 0 means the agreement between the two methods is no better than random chance.
Our score indicates fair agreement, they aren't assigning topics totally independent of each other.
"""

cohen_kappa = cohen_kappa_score(recat["Topic"], recat["new_theme"])
print(f"Cohen's Kappa Score: {cohen_kappa:.2f}")

"""Compute Change Rate (%), how often does the LLM change the topic?
54.71% of responses were reassigned to another theme by the LLM, implying substantial divergence from the original topic modeling.
"""

change_rate = (recat["Topic"] != recat["new_theme"]).mean() * 100
print(f"Percentage of responses recategorized: {change_rate:.2f}%")

"""Which original topics had the most change?

This is likely to change with an adjusted prompt! LLM over assigned original 0's to 9's.
"""

#Count changes per topic
change_counts = recat[recat["Topic"] != recat["new_theme"]]["Topic"].value_counts().sort_index()

print("Number of changes per original topic:")
print(change_counts)

#Create confusion matrix
conf_matrix = pd.crosstab(recat["Topic"], recat["new_theme"])

# Plot heatmap
plt.figure(figsize=(10, 6))
sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues")
plt.xlabel("LLM-Assigned Topic")
plt.ylabel("Original Topic")
plt.title("Comparison of Original vs. LLM Categorization")
plt.show()

recat["new_theme"].value_counts()

recat["Topic"].value_counts()